export const button_click = "button_click"
export const change_text = "change_text"
export const load_data = "load_data"
export const loading_show = "loading_show"
export const loading_hide = "loading_hide"